name: woven_by_toyota
description: "Woven by Toyota App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5+1
  get_it: ^8.2.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.9.0

flutter:
  uses-material-design: true